config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  get 'ecalcs/new'

  get 'ecalcs/create'

  get 'ecalcs/edit'

  get 'ecalcs/index'

  get 'ecalcs/show'

resources 'users'
resources 'energy'

resources 'ecalcs'

get 'login', to: 'users#login'
post 'authenticate', to: 'users#authenticate'

get 'signup', to: 'users#new'

get 'upload', to: 'ecalcs#new'
post 'import', to: 'ecalcs#index'
get ' ecalcs_show_path', to: 'ecalcs#show'

end

app/models/ecalc.rb
class Ecalc < ActiveRecord::Base
	has_attached_file :file 
	belongs_to :user
	#CSV.foreach(file.path, headers: true) do |row|
		#Ecalc.create! row.to_hash
	#end
end

app/models/energy.rb
class Energy < ActiveRecord::Base
	has_attached_file :file 
end

app/models/hourly_rate.rb
class HourlyRate < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :ecalcs
	validates :password, length: {minimum:5}, presence: {on: :create}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ecalcs_controller.rb
class EcalcsController < ApplicationController
  require 'csv'
  def new
    @ecalc=Ecalc.new
  end

  def create
   #file_data is the file. if it is file, then will use read method. if path with go to path and then use read method 
    file_data=params[:file]
    if file_data.respond_to?(:read)
        xml_contents= file_data.read
    elsif file_data.respond_to?(:path)
      xml_contents= File.read(file_data.path)
    else
        logger.error "bla error"
        redirect_to :root
    end
    p file_data
    p xml_contents
    current_user = User.find session[:user_id]
    csv=CSV.new(xml_contents.to_s, headers: true, header_converters: :all)
    #csv.to_a.map { |row| row.to_hash }
    #converted CSV into an aray of hashes
    savings_by_hour =[]
    @energy_usage = 0
    csv.each do |row|
    #convert string to date time objects(start and end times)
      row['type']= row['type'].to_string
      row['start_time'] = Chronic.parse("#{row['date']} #{row['start_time']}")
      row['end_time'] = Chronic.parse("#{row['date']} #{row['start_time']}")
      row['usage']= row['usage'].to_string
      row['units']= row['units'].to_string
      row['cost']=row['cost'].to_i
      #Ecalc.create row  
      usage= Ecalc.new row.to_hash
      usage.user = current_user
      usage.save
      p usage
      p row
      #saving for later use
      @energy_usage += row['usage']
      compare_to = HourlyRate.where time: usage.time, date: usage.date
      #make sure those are the attributes names
      result = usage.usage *compare_to.rate
      #the savings calculation
      savings_by_hour.push result
      #push the result into array for later
    end
    @whatever = current_user.ecalcs.sum('usage')
    p @whatever
  end

  def cost_static
    rate= '.07'
    usagesum=Ecalc.sum('usage')
    cost_static= :rate*:usagesum
  end

  # def cost_dynamic
  #   usage_dynamic= Ecalc.each do |row|
  #     row['start_time'] 
  #     row['usage']
  #     usage_dynamic.save
  #   end
  #   usage_rate= HourlyRate.each do |row|
  #     row['date']
  #     row['time']
  #     row['rate']
  #     usage_rate.save
    #end 
    #cost_dynamic= 
  #end




  def edit
  end

  def index
    @ecalc=Ecalc.all
  end

  def import
      Ecalc.import(params[:file])
      redirect_to ecalcs_show_path, notice:"Energy data imported"
  end 

  def ecalc_params
    params.require('ecalc').permit(:file)
  end
end

app/controllers/energy_controller.rb
# class EnergyController < ApplicationController
#   def new
#     @energy=Energy.new
#   end

#   def create
#   end

#   def index
#   end

#   #allows users to upload file
#   def import
#   	Energy.import(params[:file])
#   	redirect_to root_url, notice:"Energy data imported"
#   end 
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to login_path
    else
      flash[:notice]= "Could not create new user"
      redirect_to :back
    end
  end

  def edit
  end

  def update
  end

  def login
  end

  def authenticate
    @user=User.find_by email: params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id]=@user.id 
      redirect_to upload_path
      #redirect_to user_path(@user.id)
    else
      flash[:notice] = "Invalid username or password"
      redirect_to :back
    end
  end 

  private
  def user_params
    params.require('user').permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ecalcs_helper.rb
module EcalcsHelper
end

app/helpers/energy_helper.rb
module EnergyHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ecalcs/create.html.erb
<h1>Ecalcs#create</h1>
<p>Find me in app/views/ecalcs/create.html.erb</p>

app/views/ecalcs/edit.html.erb
<h1>Ecalcs#edit</h1>
<p>Find me in app/views/ecalcs/edit.html.erb</p>

app/views/ecalcs/index.html.erb
<h2>Import Sucessful!</h2>

<% @ecalc.find_by session[:user_id] %>
 	<p><%= @energy_usage %></p>
 	<p><%= @whatever %></p>
 	
 	




<h3>You are a good candidate for the Hourly Pricing Program!</h3>
<h5> You could have saved $5.53 on your September ComEd bill.</h5>


<a href="https://hourlypricing.comed.com/enroll/">Enroll here</a>
<br />
<a href="https://hourlypricing.comed.com/faqs/">Want to learn more?</a>

app/views/ecalcs/new.html.erb
<h2>Import a CSV of your energy usage data!</h2>

<%= form_tag import_path, multipart: true do %>

	<%= file_field_tag :file %>
	<br />
	<%= submit_tag "Import Energy Data" %>
<%end%>

<h3>How do I get a CSV file my energy Data?</h3>
<p>Step 1: Create an online ComEd account</p>
<p>Step 2: Go to the “Energy Management Page”</p>
<p>Step3: Click the large green button at the bottom of the page called “Green Button Download”.  This tool allows you to download your energy usage data in a CSV format.</p>


<h1>Ecalcs#new</h1>

app/views/ecalcs/show.html.erb
<h1>Ecalcs#show</h1>
<p>Find me in app/views/ecalcs/show.html.erb</p>

app/views/energy/create.html.erb
<h1>Energy#create</h1>
<p>Find me in app/views/energy/create.html.erb</p>

app/views/energy/index.html.erb
<h1>Energy#index</h1>
<h2>Import CSV of Data</h2>

<%= form_tag '/import' do %>

	<%= file_field_tag :file %>
	<br />
	<%= submit_tag "Import" %>
<%end%>

app/views/energy/new.html.erb
<h1>Energy#new</h1>
<p>Find me in app/views/energy/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HourlyPricingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
<img src="DeltaLumin_logo_color.jpg" alt="logo" />
<h1>Hourly Pricing Program Calculator</h1>
<%= link_to "Login", login_path %>
<%= link_to "Sign Up", signup_path %>

<%= link_to "Upload Energy Data", upload_path %>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/login.html.erb
<h2>login</h1>
<% if notice %>
	<p>
		<%= notice %>
	</p>
<% end %>
<%= form_tag authenticate_path,{method: "post"} do %>
	<input type="text" name="email" placeholder="Email Address"/>
	<br />
	<input type="password" name="password" placeholder="Enter your password" />
	<br />
	<button type="submit">Log in </button>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>


<%= form_for @user do |f| %>
	<%= f.text_field :email %>
	<br />
	<%= f.text_field :password %>
	<br />
	<%= f.text_field :password_confirmation %>
	<br />
	<%= f.submit 'Sign Up' %>

<% end %>

<h3>About the HPP Calculator:</h3>
<p> The Hourly Pricing Program calculator is a tool that is be used to assess whether you are a good candidate for ComEds Hourly Pricing Program. The tool works by looking at your historical energy usage over the past year. It calculates the annual supply charge with a fix rate and then calculates the annual supply charge with Hourly Pricing. If the Supply charge with fixed rate is greater than the supply charge with an hourly rate then you could save money by enrolling in the program! </p>

<h3>What is ComEd’s Hourly Pricing Program?</h3>
<p>ComEd’s Hourly Pricing program is an hourly electricity pricing program for residential customers that uses ComEd’s Rate BESH to determine your monthly electricity bills. The program gives you access to hourly electricity prices that are based on the ComEd Zone PJM wholesale market prices. ComEd passes on the price of electricity at cost; you simply pay the market price.</p>

<a href="https://hourlypricing.comed.com/faqs/">Want to learn more?</a>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>